CREATE TABLE IF NOT EXISTS posts (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(256) NOT NULL,
    content VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS choices (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    content VARCHAR(256) NOT NULL
);
